shared:
   image: node:20
   steps:
      - echo: echo test
jobs:
    simple:
        requires: [~commit]
        annotations:
            screwdriver.cd/virtualJob: true
    parallel:
        requires: [simple]
        annotations:
            screwdriver.cd/virtualJob: true
    join:
        requires: [parallel, sd@5398:external]
