shared:
   image: node:20
   steps:
      - echo: echo test
   annotations:
      screwdriver.cd/virtualJob: true
jobs:
    simple:
        requires: [~commit]
    parallel:
        requires: [simple]
    join:
        requires: [parallel, sd@5398:external]
