shared:
    image: node:20
    steps:
        - echo: echo test
jobs:
    success_A:
        requires: [~commit]
        annotations:
            screwdriver.cd/virtualJob: true
    fail_A:
        steps:
            - fail: exit 1
        requires: []
    parallel_A:
        requires: []
        annotations:
            screwdriver.cd/virtualJob: true
